version: '3'

services:

  emscripten-builder:
    user: ${USERID}
    image: seanmorris/php-emscripten-builder
    build:
      context: ./
      dockerfile: emscripten-builder.dockerfile
    environment:
      EMCC_CORES: 8
      ENVIRONMENT: ${ENVIRONMENT:-web}
    volumes:
      - ./:/src
      - /tmp/emsdk-cache:/emsdk/upstream/emscripten/cache/
      - ./.cache:/emsdk_portable/.data/cache/asmjs/
    command: [bash]
